name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore
        run: dotnet restore RazorComponentHelpers.sln

      - name: Build
        run: dotnet build RazorComponentHelpers.sln --configuration Release --no-restore

      - name: Pack
        run: dotnet pack src/RazorComponentHelpers/RazorComponentHelpers.csproj --configuration Release --no-restore --output ./artifacts

      - name: Push to NuGet
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate